apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-api
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: php:8.1.16
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: "users-db"