apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restricted-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "deployments/rollback"]
  verbs: ["get", "list", "watch", "rollback"]