apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-role-binding
subjects:
- kind: ServiceAccount
  name: dev-team
roleRef:
  kind: Role
  name: restricted-role
  apiGroup: rbac.authorization.k8s.io